#!/usr/bin/env bash
# init-gh-apps.sh — provision the three GitHub Apps the fleet repo needs
# before `terraform/bootstrap/fleet` can apply (PLAN §16.4).
#
# Apps created (one per loop iteration):
#   - fleet-meta          admin-class App used by env/team-bootstrap workflows
#   - stage0-publisher    narrow App used by Stage 0 to publish repo variables
#   - fleet-runners       repo-scoped App used by KEDA to scale the self-hosted
#                          runner pool (actions:read + metadata:read)
#
# The GitHub API has no headless endpoint for App creation. Each App must be
# born through the App Manifest flow, which requires exactly one human click
# in the browser to consent to the permission set. This script automates
# everything around that click:
#
#   1. Build the manifest from clusters/_fleet.yaml.
#   2. Open a localhost listener on a random port (127.0.0.1 only, 5-min TTL).
#   3. Print + open(1) the manifest URL.
#   4. Capture the redirect with the temp code.
#   5. Exchange the code via `gh api .../conversions` for App credentials.
#   6. Install the App on the fleet repo.
#   7. Persist credentials to ./.gh-apps.state.json (mode 0600, gitignored).
#
# After all three Apps exist, the script:
#   - Writes ./.gh-apps.auto.tfvars (gitignored) for Stage 0 to consume.
#   - Patches clusters/_fleet.yaml with `github_app.fleet_runners.{app_id,
#     installation_id}` so `bootstrap/fleet` apply just works.
#   - Self-deletes (only on a fully successful run).
#
# Idempotent: if .gh-apps.state.json already records all three Apps, the
# script re-emits the tfvars overlay + _fleet.yaml patch and exits 0
# without prompting.
#
# Usage:
#   ./init-gh-apps.sh              # interactive: opens browser, waits for clicks
#   ./init-gh-apps.sh --no-open    # don't shell out to open(1) — print URL only
#   ./init-gh-apps.sh --port N     # bind listener to a specific port
#   ./init-gh-apps.sh --keep       # don't self-delete on success (debug aid)
#
# Prereqs:
#   - clusters/_fleet.yaml exists (run ./init-fleet.sh first).
#   - `gh` CLI authenticated with `repo:admin` + `admin:org` scopes
#     (via `gh auth login`, or $GH_TOKEN / $GITHUB_TOKEN env var).
#   - python3, git.
#
# See PLAN §16.4 and docs/adoption.md §4.

set -euo pipefail

die()  { printf 'init-gh-apps: %s\n' "$*" >&2; exit 1; }
warn() { printf 'init-gh-apps: %s\n' "$*" >&2; }
info() { printf '  %s\n' "$*"; }

# ---- flag parsing -----------------------------------------------------------

NO_OPEN=0
KEEP=0
PORT=0  # 0 == random

while (($#)); do
  case "$1" in
    --no-open) NO_OPEN=1; shift ;;
    --keep)    KEEP=1;    shift ;;
    --port)    PORT="${2:?--port needs a number}"; shift 2 ;;
    --port=*)  PORT="${1#*=}"; shift ;;
    -h|--help) sed -n '2,46p' "$0"; exit 0 ;;
    *) die "unknown flag: $1" ;;
  esac
done

# ---- preflight --------------------------------------------------------------

command -v python3 >/dev/null 2>&1 || die "python3 is required"
command -v gh      >/dev/null 2>&1 || die "gh CLI is required (https://cli.github.com)"
command -v git     >/dev/null 2>&1 || die "git is required"

repo_root="$(cd "$(dirname "$0")" && pwd)"
cd "$repo_root"

fleet_yaml="$repo_root/clusters/_fleet.yaml"
state_file="$repo_root/.gh-apps.state.json"
tfvars_file="$repo_root/.gh-apps.auto.tfvars"

[[ -f "$fleet_yaml" ]] || die "clusters/_fleet.yaml not found — run ./init-fleet.sh first"

# Auth: don't hard-require $GITHUB_TOKEN — `gh` resolves credentials from
# `gh auth login` (keyring), $GH_TOKEN, or $GITHUB_TOKEN in that order.
# Just verify that `gh api` actually works; the prereq scopes
# (repo:admin + admin:org) are enforced by the first failing call, which
# is fine — we want to fail fast *here* on the smoke test, not mid-flow.
if ! gh api user -q .login >/dev/null 2>&1; then
  die "gh CLI cannot authenticate — run 'gh auth login' or export GH_TOKEN / GITHUB_TOKEN (requires 'repo:admin' + 'admin:org' scopes)"
fi

# ---- load _fleet.yaml -------------------------------------------------------
#
# We need: fleet.github_org, fleet.github_repo. Pure-python YAML extraction
# (no yq dependency); the values we need are top-level scalars in a known
# block, so a tiny parser via PyYAML is overkill — but PyYAML is in the
# Python stdlib? No. So we use a minimal regex extractor instead. This file
# is generated by init/, so its shape is stable.

read_yaml_scalar() {
  # Args: <yaml-file> <dotted-path>   e.g. fleet.github_org
  #
  # Minimal YAML key extractor sufficient for the well-known shape that
  # init/templates/_fleet.yaml.tftpl emits: every key is `<indent><name>:
  # <value>` with two-space nesting and no flow-style maps. Avoids a hard
  # dependency on yq.
  python3 - "$1" "$2" <<'PY'
import re, sys
path, dotted = sys.argv[1], sys.argv[2].split('.')
text = open(path).read()
indent = 0
remaining = text
for i, key in enumerate(dotted):
    # `[ \t]` instead of `\s` so the value match cannot eat the newline that
    # ends this key's line (which would silently jump into the next key).
    pat = re.compile(rf'^{" " * indent}{re.escape(key)}:[ \t]*(.*)$', re.MULTILINE)
    m = pat.search(remaining)
    if not m:
        sys.stderr.write(f"key not found: {'.'.join(dotted[:i+1])}\n"); sys.exit(2)
    if i == len(dotted) - 1:
        val = m.group(1).strip().strip('"').strip("'")
        val = re.sub(r'\s+#.*$', '', val)
        print(val)
        sys.exit(0)
    start = m.end()
    sub = remaining[start:]
    end_pat = re.compile(rf'^(?: {{0,{indent}}})\S', re.MULTILINE)
    em = end_pat.search(sub)
    remaining = sub[: em.start()] if em else sub
    indent += 2
PY
}

github_org=$(read_yaml_scalar "$fleet_yaml" fleet.github_org) \
  || die "failed to read fleet.github_org from $fleet_yaml"
github_repo=$(read_yaml_scalar "$fleet_yaml" fleet.github_repo) \
  || die "failed to read fleet.github_repo from $fleet_yaml"

[[ -n "$github_org"  ]] || die "fleet.github_org is empty in $fleet_yaml"
[[ -n "$github_repo" ]] || die "fleet.github_repo is empty in $fleet_yaml"

info "Target org/repo: $github_org/$github_repo"

# Determine if the org is actually an org (vs a user); affects which manifest
# URL the operator is sent to and which install endpoint applies.
owner_type="$(gh api "users/$github_org" -q .type 2>/dev/null || echo Organization)"
case "$owner_type" in
  Organization|User) : ;;
  *) warn "could not resolve owner type for $github_org; defaulting to Organization" ;;
esac

# ---- state-file helpers -----------------------------------------------------

state_get() {
  # Args: <slug> <field>  ->  prints field or empty string
  [[ -f "$state_file" ]] || { echo ""; return 0; }
  python3 - "$state_file" "$1" "$2" <<'PY'
import json, sys
try:
    s = json.load(open(sys.argv[1]))
except Exception:
    print(""); sys.exit(0)
print((s.get(sys.argv[2], {}) or {}).get(sys.argv[3], "") or "")
PY
}

state_set() {
  # Args: <slug> <json-payload-as-string>
  python3 - "$state_file" "$1" "$2" <<'PY'
import json, os, sys
path, slug, payload = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    s = json.load(open(path))
except Exception:
    s = {}
s[slug] = json.loads(payload)
# Mode 0600 — these are App secrets.
fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, 'w') as f:
    json.dump(s, f, indent=2, sort_keys=True)
PY
}

# ---- App definitions --------------------------------------------------------
#
# Tuple per App: <slug> <permissions-json> <events-json> <tfvars-prefix>
# Permissions reference: https://docs.github.com/rest/apps/apps#permissions
#
# Permission keys MUST match the App Manifest schema exactly (singular,
# lowercase; values "read" or "write"). The repo-vs-org distinction is
# encoded by `default_repository_permissions: false` and the per-key
# placement in the manifest below.

apps_meta_perms='{"administration":"write","environments":"write","actions_variables":"write","secrets":"write","contents":"write"}'
apps_stage0_perms='{"actions_variables":"write"}'
apps_runners_perms='{"actions":"read","metadata":"read"}'

# fleet-meta and stage0-publisher write to the repo only; fleet-runners reads.
# All three are repo-scoped (no organization permissions requested).

# We expose a parallel array because portable bash lacks associative-array
# ordering guarantees.
APP_SLUGS=("fleet-meta" "stage0-publisher" "fleet-runners")
APP_PERMS=("$apps_meta_perms" "$apps_stage0_perms" "$apps_runners_perms")
APP_PREFIX=("fleet_meta_app" "stage0_publisher_app" "fleet_runners_app")

# ---- manifest flow per App --------------------------------------------------

create_app() {
  local slug="$1" perms="$2"
  local existing_id
  existing_id=$(state_get "$slug" "id")
  if [[ -n "$existing_id" ]]; then
    info "✓ $slug already in $state_file (id=$existing_id) — skipping"
    return 0
  fi

  info "Creating GitHub App: $slug"

  # Listener: random port if PORT==0; bind to 127.0.0.1 only; 5-minute timeout.
  # We launch the listener as a background python3 invocation that writes the
  # captured redirect query string to a temp file then exits.
  #
  # Cleanup strategy: avoid `trap ... RETURN` — RETURN traps set inside a
  # function interact unpredictably with `set -u` and with later function
  # invocations (see Copilot review feedback). Instead, define a local
  # cleanup closure, call it explicitly on the success path, and install a
  # narrowly-scoped EXIT trap that only runs if the script dies mid-function
  # (because `die` goes straight to `exit 1` without returning).
  local cb_file port_file listener_pid=""
  cb_file=$(mktemp -t gh-apps-cb.XXXXXX)
  port_file=$(mktemp -t gh-apps-port.XXXXXX)

  _create_app_cleanup() {
    [[ -n "${listener_pid:-}" ]] && kill "$listener_pid" 2>/dev/null || true
    rm -f "${cb_file:-}" "${port_file:-}" "${form_file:-}"
  }
  # Install as EXIT trap: only fires if we exit abnormally (die → exit 1).
  # The final explicit call at the bottom of this function clears it via
  # `trap - EXIT` before returning normally.
  trap _create_app_cleanup EXIT

  # Random nonce so we can verify the redirect is the one we initiated.
  local nonce
  nonce=$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')

  python3 - "$PORT" "$cb_file" "$port_file" "$nonce" <<'PY' &
import http.server, socket, sys, threading, time, urllib.parse

requested_port, cb_file, port_file, nonce = (
    int(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4]
)

class H(http.server.BaseHTTPRequestHandler):
    captured = False
    def log_message(self, *a, **kw): pass
    def do_GET(self):
        u = urllib.parse.urlparse(self.path)
        q = urllib.parse.parse_qs(u.query)
        if u.path != '/cb' or q.get('state', [''])[0] != nonce:
            self.send_response(400); self.end_headers()
            self.wfile.write(b"bad request"); return
        with open(cb_file, 'w') as f:
            f.write(q.get('code', [''])[0])
        self.send_response(200); self.end_headers()
        self.wfile.write(
            b"<html><body><h2>GitHub App created.</h2>"
            b"<p>You may close this tab and return to the terminal.</p>"
            b"</body></html>"
        )
        H.captured = True

srv = http.server.HTTPServer(('127.0.0.1', requested_port), H)
with open(port_file, 'w') as f:
    f.write(str(srv.server_address[1]))
# 5-minute timeout: poll handle_request with a deadline.
srv.timeout = 1
deadline = time.time() + 300
while not H.captured and time.time() < deadline:
    srv.handle_request()
sys.exit(0 if H.captured else 2)
PY
  listener_pid=$!

  # Wait for the listener to write its bound port.
  local waited=0 port=""
  while [[ -z "$port" && $waited -lt 50 ]]; do
    sleep 0.1
    [[ -s "$port_file" ]] && port=$(cat "$port_file")
    waited=$((waited + 1))
  done
  [[ -n "$port" ]] || die "listener failed to bind a port"

  # Build the manifest. The manifest shape is documented at
  # https://docs.github.com/apps/sharing-github-apps/registering-a-github-app-using-url-parameters
  local manifest_json
  manifest_json=$(python3 - "$slug" "$perms" "$port" <<'PY'
import json, sys
slug, perms_json, port = sys.argv[1], sys.argv[2], int(sys.argv[3])
manifest = {
    "name": slug,
    "url": f"http://127.0.0.1:{port}/cb",
    "redirect_url": f"http://127.0.0.1:{port}/cb",
    "public": False,
    "default_permissions": json.loads(perms_json),
    "default_events": [],
}
print(json.dumps(manifest))
PY
  )

  # The manifest URL is a GET to /settings/apps/new with the manifest as a
  # form value. GitHub renders a confirmation page; the operator clicks
  # "Create GitHub App" once, after which they are redirected to our listener.
  # We pre-build a tiny HTML form because the manifest payload exceeds query-
  # string limits.
  local form_file=""
  form_file=$(mktemp -t gh-apps-form.XXXXXX).html
  python3 - "$github_org" "$owner_type" "$nonce" "$manifest_json" "$form_file" <<'PY'
import html, json, sys
org, owner_type, nonce, manifest, out = sys.argv[1:6]
if owner_type == "Organization":
    action = f"https://github.com/organizations/{org}/settings/apps/new?state={nonce}"
else:
    action = f"https://github.com/settings/apps/new?state={nonce}"
with open(out, 'w') as f:
    f.write(
        "<!doctype html><html><body onload=\"document.forms[0].submit()\">"
        f"<form method='post' action='{html.escape(action)}'>"
        f"<input type='hidden' name='manifest' value='{html.escape(manifest)}'>"
        "<noscript><button type='submit'>Click to continue to GitHub</button></noscript>"
        "</form></body></html>"
    )
PY

  echo ""
  echo "  Open this file in a browser to create the '$slug' App:"
  echo "    file://$form_file"
  echo ""
  echo "  After clicking 'Create GitHub App', you'll be redirected to the"
  echo "  local listener at http://127.0.0.1:$port/cb (5-minute timeout)."
  echo ""

  if [[ $NO_OPEN -eq 0 ]] && [[ -t 1 ]] && command -v open >/dev/null 2>&1; then
    open "file://$form_file" || true
  elif [[ $NO_OPEN -eq 0 ]] && [[ -t 1 ]] && command -v xdg-open >/dev/null 2>&1; then
    xdg-open "file://$form_file" >/dev/null 2>&1 || true
  fi

  # Wait for the listener to capture the code. On timeout, `die` triggers
  # the EXIT trap which runs _create_app_cleanup.
  if ! wait "$listener_pid"; then
    die "listener timed out waiting for the redirect — re-run when ready"
  fi

  local code
  code=$(cat "$cb_file")
  [[ -n "$code" ]] || die "listener returned an empty code"

  # Exchange code for App credentials. Single-use, ~10 minute TTL.
  info "Exchanging temp code for App credentials"
  local conv_json
  if ! conv_json=$(gh api -X POST "/app-manifests/$code/conversions" 2>&1); then
    die "manifest exchange failed: $conv_json"
  fi

  # Persist credentials to state immediately — the API returns them once.
  local payload
  payload=$(python3 - <<PY
import json, sys
c = json.loads('''$conv_json''')
out = {
    "id": c.get("id"),
    "slug": c.get("slug"),
    "name": c.get("name"),
    "client_id": c.get("client_id"),
    "client_secret": c.get("client_secret"),
    "pem": c.get("pem"),
    "webhook_secret": c.get("webhook_secret"),
    "html_url": c.get("html_url"),
}
print(json.dumps(out))
PY
)
  state_set "$slug" "$payload"
  info "✓ $slug created and saved to .gh-apps.state.json"

  # Normal-path cleanup: remove temp files and clear the EXIT trap so it
  # doesn't fire on the next function's scope.
  _create_app_cleanup
  trap - EXIT
}

install_app() {
  local slug="$1"
  local app_slug app_id existing_install
  app_slug=$(state_get "$slug" "slug")
  app_id=$(state_get "$slug" "id")
  [[ -n "$app_id" ]] || die "internal: no id recorded for $slug"

  # Check whether the App is already installed on the fleet repo.
  existing_install=$(state_get "$slug" "installation_id")
  if [[ -n "$existing_install" ]]; then
    info "✓ $slug install already recorded (id=$existing_install)"
    return 0
  fi

  info "Locating installation of $app_slug (app_id=$app_id) on $github_org"

  # Find the installation_id for THIS specific App on the fleet org/user.
  # The obvious-looking `repos/<org>/<repo>/installation` endpoint requires
  # App-JWT auth (not a PAT) and returns 404 with PAT auth. Instead, list
  # all App installations on the owner scope and filter by app_id — this
  # works with the `admin:org` PAT scope the script already requires.
  lookup_install_id() {
    local base="/users/$github_org/installations"
    [[ "$owner_type" == "Organization" ]] && base="/orgs/$github_org/installations"
    gh api --paginate "$base" \
      --jq ".installations[]? // .[] | select(.app_id==$app_id) | .id" \
      2>/dev/null | head -n1
  }

  local install_id
  install_id=$(lookup_install_id)

  if [[ -z "$install_id" ]]; then
    # Not installed yet. Direct the operator to install it.
    local install_url="https://github.com/apps/$app_slug/installations/new"
    echo ""
    echo "  Install '$app_slug' on $github_org/$github_repo:"
    echo "    $install_url"
    echo ""
    if [[ $NO_OPEN -eq 0 ]] && [[ -t 1 ]]; then
      if command -v open >/dev/null 2>&1; then open "$install_url" || true
      elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$install_url" >/dev/null 2>&1 || true
      fi
    fi
    read -r -p "  Press Enter once you've completed the install... " _ </dev/tty || true
    install_id=$(lookup_install_id)
  fi

  [[ -n "$install_id" ]] \
    || die "could not resolve installation id for $app_slug (app_id=$app_id) on $github_org"

  # Patch state file with installation_id.
  python3 - "$state_file" "$slug" "$install_id" <<'PY'
import json, os, sys
path, slug, iid = sys.argv[1], sys.argv[2], sys.argv[3]
s = json.load(open(path))
s[slug]["installation_id"] = int(iid)
fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, 'w') as f:
    json.dump(s, f, indent=2, sort_keys=True)
PY
  info "✓ $slug installed (installation_id=$install_id)"
}

# ---- main loop --------------------------------------------------------------

for i in "${!APP_SLUGS[@]}"; do
  create_app "${APP_SLUGS[$i]}" "${APP_PERMS[$i]}"
  install_app "${APP_SLUGS[$i]}"
done

# ---- emit tfvars overlay ----------------------------------------------------
#
# Stage 0 declares matching variable blocks; tf-apply.yaml symlinks/copies
# this file into terraform/stages/0-fleet/ so terraform plan/apply picks it
# up as an additional variable source. Heredocs preserve the PEM exactly.

info "Writing $tfvars_file"
python3 - "$state_file" "$tfvars_file" <<'PY'
import json, os, sys
state_path, out_path = sys.argv[1], sys.argv[2]
s = json.load(open(state_path))

mapping = [
    ("fleet-meta",        "fleet_meta_app"),
    ("stage0-publisher",  "stage0_publisher_app"),
    ("fleet-runners",     "fleet_runners_app"),
]

lines = [
    "# Generated by ./init-gh-apps.sh — do not edit by hand.",
    "# Consumed by terraform/stages/0-fleet via tf-apply.yaml.",
    "# Gitignored (see .gitignore).",
    "",
]
for slug, prefix in mapping:
    a = s[slug]
    lines += [
        f'{prefix}_id              = "{a["id"]}"',
        f'{prefix}_client_id       = "{a["client_id"]}"',
        f'{prefix}_installation_id = "{a["installation_id"]}"',
        f'{prefix}_pem             = <<EOT',
        a["pem"].rstrip("\n"),
        "EOT",
        f'{prefix}_webhook_secret  = "{a["webhook_secret"]}"',
        "",
    ]

fd = os.open(out_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, 'w') as f:
    f.write("\n".join(lines))
PY

# ---- patch _fleet.yaml: github_app.fleet_runners.{app_id, installation_id} ---
#
# bootstrap/fleet's runner module validates these are non-empty before apply
# (see terraform/bootstrap/fleet/main.runner.tf). The script is the only
# place that knows the values, so we write them back into the YAML.
# Surgical line-level edit (no YAML reformat); the keys are stable because
# init/templates/_fleet.yaml.tftpl emits them with two-space indent.

info "Patching $fleet_yaml with fleet-runners IDs"
python3 - "$fleet_yaml" "$state_file" <<'PY'
import json, pathlib, re, sys
yaml_path, state_path = sys.argv[1], sys.argv[2]
state = json.load(open(state_path))
runners = state["fleet-runners"]
app_id = str(runners["id"])
inst_id = str(runners["installation_id"])

p = pathlib.Path(yaml_path)
text = p.read_text()

def replace(text, key, value):
    pat = re.compile(rf'^(\s+){re.escape(key)}:\s*"[^"]*"(\s*(?:#.*)?)$', re.MULTILINE)
    new, n = pat.subn(rf'\g<1>{key}: "{value}"\g<2>', text, count=1)
    if n == 0:
        sys.stderr.write(f"could not find '{key}' in {yaml_path}; leave manual edit\n")
        return text
    return new

text = replace(text, "app_id", app_id)
text = replace(text, "installation_id", inst_id)
p.write_text(text)
PY

# ---- self-cleanup -----------------------------------------------------------

echo ""
echo "✔ All three GitHub Apps created, installed, and recorded."
echo "  - State:   $state_file (mode 0600, gitignored)"
echo "  - Tfvars:  $tfvars_file (mode 0600, gitignored)"
echo "  - YAML:    $fleet_yaml patched with fleet-runners IDs"
echo ""
echo "  Next:"
echo "    1. Commit the _fleet.yaml change."
echo "    2. Run terraform -chdir=terraform/bootstrap/fleet apply."
echo "    3. After Stage 0 has applied, you may delete:"
echo "         $state_file"
echo "         $tfvars_file"
echo ""

if [[ $KEEP -eq 0 ]]; then
  rm -f "$0"
fi
