# stages/0-fleet/backend.tf
#
# Partial backend config — values arrive via `terraform init
# -backend-config=backend.hcl`, generated by the
# `.github/actions/tf-backend-config` composite action from env-scoped
# repo vars (`TFSTATE_RESOURCE_GROUP`, `TFSTATE_STORAGE_ACCOUNT`,
# `TFSTATE_CONTAINER`, `AZURE_SUBSCRIPTION_ID`) published by
# `bootstrap/fleet` to the `fleet-stage0` GH environment.
#
# Stage 0 always writes to the fleet-wide state container
# (`tfstate-fleet`) under `key = stage0/fleet.tfstate`.
#
# `subscription_id` is the STATE subscription
# (`_fleet.yaml.state.subscription_id`). The action defaults it to
# `AZURE_SUBSCRIPTION_ID`; multi-subscription adopters should override
# via the action's `subscription-id` input. If omitted, the azurerm
# backend falls back to `ARM_SUBSCRIPTION_ID` or the az-CLI context,
# which can silently target the wrong subscription under OIDC.
#
# The empty backend block in providers.tf is the anchor; this file is
# intentionally comment-only.
