# stages/1-cluster/backend.tf
#
# Partial backend config — values arrive via `terraform init
# -backend-config=backend.hcl`, generated by the
# `.github/actions/tf-backend-config` composite action from env-scoped
# repo vars published by `bootstrap/environment` to each
# `fleet-<env>` GH environment.
#
# `TFSTATE_CONTAINER` resolves to the per-env container
# `tfstate-<env>` (not the fleet-wide `tfstate-fleet`); per-env
# containers keep env teardown atomic and stop a prod apply from
# touching nonprod state. `TFSTATE_RESOURCE_GROUP` /
# `TFSTATE_STORAGE_ACCOUNT` are fleet-wide values re-published per-env
# so every job's environment context resolves them.
#
# Conventional `state-key`:
#   <region>/<cluster_name>/stage1.tfstate
#
# Backend block anchor lives in providers.tf; this file is intentionally
# comment-only.
